version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/usr/src
      - node_modules_client:/usr/src/node_modules
    stdin_open: true
    tty: true
    ports:
      - '8080:8080'
    command: [yarn, serve]
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - 3000:3000
    volumes:
      - ./server:/usr/src
      - node_modules_server:/usr/src/node_modules
    stdin_open: true
    tty: true
    command: [yarn, serve]

volumes:
  node_modules_client:
  node_modules_server:
