name: lint and test server on push
on:
  pull_request:
    types: [opened, synchronize]

defaults:
  run:
    working-directory: server

jobs:
  lint_and_test_server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['14.15.4']
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: run lint and test
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test:unit
      - run: yarn lint
